export const FETCH_DROPDOWN_DATA = "FETCH_DROPDOWN_DATA";
export const FETCH_DROPDOWN_ERROR = "FETCH_DROPDOWN_ERROR";

export const SELECT_POKEMON = "SELECT_POKEMON";
export const SET_STARTING_LEVEL = "SET_STARTING_LEVEL";
export const SET_TARGET_LEVEL = "SET_TARGET_LEVEL";

export const VALIDATE_SUCCESS = "VALIDATE_SUCCESS";
export const VALIDATE_ERROR = "VALIDATE_ERROR";

export const ERROR_DISMISSED = "ERROR_DISMISSED";
